behaviors:
  POCAVegan:
    trainer_type: poca
    
    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      learning_rate_schedule: constant
      
      # POCA-specific hyperparameters
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    
    # Configuration of the neural network
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 2
    
    # Trainer configurations common to all trainers
    max_steps: 15000000
    time_horizon: 1000
    summary_freq: 10000    
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false
    init_path: null
          
    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99
    
    # self-play
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 50000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
      
  POCACarnivore:
    trainer_type: poca
    
    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      learning_rate_schedule: constant
      
      # POCA-specific hyperparameters
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    
    # Configuration of the neural network
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 2
    
    # Trainer configurations common to all trainers
    max_steps: 30000000
    time_horizon: 1000
    summary_freq: 10000    
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false
    init_path: null
          
    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99
    
    # self-play
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 10000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0