behaviors:
  PPOCarnivore:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 5120
      buffer_size: 40960
      learning_rate: 0.001
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 2

    # Trainer configurations common to all trainers
    max_steps: 15000000
    time_horizon: 1000
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false
    init_path: null

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99

      # curiosity module
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 0.0003