behaviors:
  SACCarnivore:
    trainer_type: sac

    # Trainer configs common to PPO/SAC (excluding reward signals)
    # same as PPO config

    # SAC-specific configs (replaces the hyperparameters section above)
    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 512
      buffer_size: 100000
      learning_rate: 0.0001
      learning_rate_schedule: constant

      # SAC-specific hyperparameters
      buffer_init_steps: 5000
      tau: 0.005
      steps_per_update: 5.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 5.0

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 2

    # Trainer configurations common to all trainers
    max_steps: 3000000
    time_horizon: 1000
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false
    init_path: null

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99

      # curiosity module
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 0.0003